TITLE_1: SEL0616
TITLE_2: Princípios de Comunicação
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro AA …</li>
    <li>Artigo BB …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/SEL0616-Principios-De-Comunicacao
HERO_FILE: principios-de-comunicacao.png